env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - prettier
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  project: ./tsconfig.json
  sourceType: module
plugins:
  - react
  - react-hooks
  - '@typescript-eslint'
settings:
  react:
    version: detect
rules:
  react/jsx-uses-react: error
  react/jsx-uses-vars: error
  react/react-in-jsx-scope: off
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
